### ISSUE TITLE
Colors aren't right

### ISSUE THREAD

**Issue by duganchen** [ianchesal/nord-fzf#1]
The colors don't look right in my Kitty terminal. Here's what @arcticestudio's Igloo project uses, which does look right:

```
  --color bg:#2e3440,bg+:#4c566a,fg:#e5e9f0
  --color fg+:#eceff4,hl:#88c0d0,hl+:#81a1c1
  --color preview-bg:#2e3440,preview-fg:#e5e9f0
  --color border:#4c566a,gutter:#3b4252,header:#88c0d0
  --color info:#88c0d0,marker:#88c0d0,pointer:#81a1c1
  --color prompt:#88c0d0,spinner:#88c0d0
```

**Comment by ianchesal** [comment]
Colors are mostly correct. (`#3b4251` should actually be `#3b4252` -- off-by-one error...)

They all come from the pallette defined by the theme. Reference is here: https://www.nordtheme.com/docs/colors-and-palettes

Feel free to use other colors if you prefer a different look. There's nothing official about my preferences here.

**Comment by duganchen** [comment]
If it does look right to you with the background being nord1 and not nord0, then I'm curious as to what terminal setup you're using. I tested with nord-kitty and nord-xresources on Linux.

**Comment by ianchesal** [comment]
It looks exactly as it does in [the screen shot in the readme](https://github.com/ianchesal/nord-fzf/blob/master/nord-fzf.png).

[Here are my colour settings for iTerm2](https://github.com/ianchesal/dotfiles/blob/main/iterm/Nord.itermcolors).

<img width="579" alt="Screen Shot 2020-09-20 at 9 03 46 AM" src="https://user-images.githubusercontent.com/291808/93715764-33837580-fb20-11ea-88d4-419cdde11389.png">

**Comment by duganchen** [comment]
Oh, so you wrote your own itermcolors and wrote the FZF colors to match?

Your iterm colors are wrong. I just checked what [Nord iTerm2](https://github.com/arcticicestudio/nord-iterm2) uses for the background. It's nord0. Not nord1.

<img width="927" alt="Screen Shot 2020-09-20 at 11 05 03 AM" src="https://user-images.githubusercontent.com/447610/93718477-71d56080-fb31-11ea-9495-06d95f484b53.png">

**Comment by ianchesal** [comment]
> Oh, so you wrote your own itermcolors and wrote the FZF colors to match?

Yes.

> Your iterm colors are wrong.

They are not wrong. They are exactly correct for the way I wanted them set.

Importing the official iTerm 2 colour profile you linked to shows my current background colour setting matches the suggested setting exactly.

What I have:

<img width="1009" alt="Screen Shot 2020-09-20 at 12 47 32 PM" src="https://user-images.githubusercontent.com/291808/93720729-c1bb2400-fb3f-11ea-8ba7-2dac23510cc5.png">

What Article Studio proposes:

<img width="959" alt="Screen Shot 2020-09-20 at 12 48 44 PM" src="https://user-images.githubusercontent.com/291808/93720744-d7c8e480-fb3f-11ea-8040-360c07207045.png">

They are the same.

In any case, if you don't like the pallette colours I've choosen, don't use them.
